import logging
from airflow import DAG 
from datetime import datetime
from airflow.providers.postgres.operators.postgres import PostgresOperator
from airflow.providers.postgres.hooks.postgres import PostgresHook
from airflow.operators.python import PythonOperator
with DAG('exemplo1_sql', start_date=datetime(2023,3,24), schedule_interval="@once", catchup=False) as dag:
    cria_tabela = PostgresOperator(
        task_id='criar_tabela',
        postgres_conn_id='postgres_default',
        sql = """
            CREATE TABLE IF NOT EXISTS TB_CLIENTE(
                ID INT GENERATED BY DEFAULT AS IDENTITY,
                nome  VARCHAR NOT NULL,
                dt date
            )
            """
    )

    insere_dados = PostgresOperator(
        task_id = 'inserir_dados',
        postgres_conn_id = 'postgres_default',
        sql = "INSERT INTO TB_CLIENTE (nome, dt) values ('Luiz Zibido', CURRENT_DATE)"
    )

cria_tabela >> insere_dados